// Sprites des objets de décor (ancrés en bas, sauf « surface »).
import type { DecorId } from '../../data/decor';
import type { SpriteDef } from '../SpriteFactory';

export const DECOR_SPRITES: Record<DecorId, SpriteDef> = {
  // ------------------------------------------------------------- Récif
  live_rock: {
    palette: { R: '#8e8497', r: '#6c6378', p: '#ff8fb0', P: '#e0608a' },
    rows: [
      '......rrrr......',
      '....rrRRRrrp....',
      '..prrRRRRRRrr...',
      '.rRRRRpPRRRRRr..',
      'rRRRRRRRRRRpRRr.',
      'rRRpRRRRRRRRRRRr',
      'rRRRRRRRRpPRRRRr',
      'rrRRRRRRRRRRRRrr',
      '.rrrrrrrrrrrrrr.',
    ],
  },
  anemone: {
    palette: { t: '#c84fd0', p: '#ff9ec8', P: '#e0709e', b: '#8e6a5a' },
    rows: [
      '..t..t.t..t...',
      '.tpt.tpt.tpt..',
      '.pp.tpptpp.pt.',
      'tpp.pppppp.ppt',
      '.pppppppppppp.',
      '..pppppppppp..',
      '...PPPPPPPP...',
      '...PPPPPPPP...',
      '....PPPPPP....',
      '....bbbbbb....',
      '...bbbbbbbb...',
    ],
  },
  branch_coral: {
    palette: { y: '#ffb88a', o: '#ff7a4a', O: '#9a8a80' },
    rows: [
      '..y.....y....',
      '..o..y..o..y.',
      '.oo..o.oo..o.',
      '..o..oo.o.oo.',
      '..oo.o..ooo..',
      '...o.o..o....',
      '...ooo.oo..o.',
      '....oo.o..oo.',
      '....oooo.oo..',
      '.....ooooo...',
      '......ooo....',
      '......oOo....',
      '.....OOOOO...',
      '....OOOOOOO..',
    ],
  },
  brain_coral: {
    palette: { g: '#9fbf4a', G: '#d8e87a', r: '#8e8497' },
    rows: [
      '....gggggg....',
      '..gGgGGgGgGg..',
      '.gGGgGgGGgGGg.',
      'gGgGGgGGgGgGGg',
      'gGGgGGgGgGGgGg',
      'gGgGGgGgGGgGGg',
      '.rrrrrrrrrrrr.',
      'rrrrrrrrrrrrrr',
    ],
  },
  seagrass: {
    palette: { g: '#6fcf6a', G: '#3f9f4a', s: '#d8bf85' },
    rows: [
      '..g.....g...',
      '..g..g..g...',
      '.gG..g..Gg..',
      '.gG..gG.Gg.g',
      '..G.gG..G..g',
      '..Gg.G.gG.gG',
      '..G..G.g..G.',
      '.gG..Gg..gG.',
      '.g.G.G...G..',
      '...G.G.g.G..',
      '...GgG.gGG..',
      '....GG..G...',
      '....GGgGG...',
      '....sGGGs...',
      '...ssssssss.',
    ],
  },
  gorgonian: {
    palette: { p: '#c77ae0', P: '#8a3fb0', r: '#8e8497' },
    rows: [
      '...p.p..p.p...',
      '..pPpPppPpPp..',
      '.pPpPpPPpPpPp.',
      'pPpPpPpPPpPpPp',
      '.pPpPpPpPpPpP.',
      'pPpPpPPpPPpPpp',
      '.pPpPpPpPpPpP.',
      '..pPpPpPpPpP..',
      '...pPpPPpPp...',
      '....pPpPpP....',
      '.....pPPp.....',
      '......PP......',
      '......PP......',
      '......PP......',
      '.....rrrr.....',
      '....rrrrrr....',
    ],
  },
  giant_clam: {
    palette: { b: '#2a6fd8', B: '#4fc3f7', c: '#9ff0ff', S: '#e8dcc8', s: '#c8b8a0', k: '#8a7a68' },
    rows: [
      '..kkkkkkkkkk..',
      '.kbBbBbBbBbBk.',
      'kbBcBcBcBcBcBk',
      'kSSSSSSSSSSSSk',
      '.kSsSsSsSsSsk.',
      '..kSSSSSSSSk..',
      '...kkkkkkkk...',
    ],
  },
  treasure: {
    palette: { b: '#6a3f1f', B: '#9a5a2a', y: '#f0c040', Y: '#fff080', k: '#3a2010' },
    rows: [
      '..bbbbbbbbb..',
      '.bBBBBBBBBBb.',
      'bBByBBBBByBBb',
      'bbbbbbbbbbbbb',
      'yyyyyyYyyyyyy',
      'bBBBBByBBBBBb',
      'bBBBBBkBBBBBb',
      'bBByBBBBByBBb',
      'bBBBBBBBBBBBb',
      'bbbbbbbbbbbbb',
    ],
  },

  // ---------------------------------------------------------- Amazonie
  stones: {
    palette: { G: '#b0a898', g: '#847c6e', w: '#d6d0c4' },
    rows: [
      '...gg.........',
      '..gwGg...gg...',
      '.gGGGGg.gwGg..',
      'gGGGGGGgGGGGg.',
      'gGGGGGGgGGGGGg',
      '.ggggggggggggg',
    ],
  },
  sand_bank: {
    palette: { S: '#f0e2c0', s: '#d8c49a' },
    rows: [
      '......ssssss......',
      '...ssSSSSSSSSss...',
      '.ssSSSSsSSSSSSSss.',
      'sSSSSSSSSSSsSSSSSs',
    ],
  },
  sword_plant: {
    palette: { g: '#5fbf4a', G: '#2f8f3a', s: '#9f7f55', S: '#c9a878' },
    rows: [
      '......g.......',
      '..g...gG...g..',
      '..gG..gG..Gg..',
      '...gG.gG.Gg...',
      '.g..gGgGGg..g.',
      '.gG..gGGg..Gg.',
      '..gG.gGGg.Gg..',
      '...gGgGGgGg...',
      '....gGGGGg....',
      '.....gGGg.....',
      '......GG......',
      '......GG......',
      '.....sssS.....',
      '....ssssss....',
    ],
  },
  vallisneria: {
    palette: { g: '#6fcf5a', G: '#3f9f3a', s: '#9f7f55' },
    rows: [
      '..g.......',
      '..g....g..',
      '..g...g...',
      '.g..g.g...',
      '.g..g..g..',
      '.g..g..g.g',
      '..g.g..g.g',
      '..g..g.g.g',
      '..g..g.gg.',
      '..gg.g..g.',
      '...g.g..g.',
      '...g..g.g.',
      '...g..g.g.',
      '...gg.g.g.',
      '....g.gg..',
      '....g.g...',
      '....gGg...',
      '....gGg...',
      '....GgG...',
      '....GGG...',
      '...ssss...',
      '..ssssss..',
    ],
  },
  floating: {
    palette: { G: '#8fdf6a', g: '#5faf4a', r: '#c8b89a' },
    rows: [
      '.GGg..gGG...gGGg..',
      'gGGGgGGGGggGGGGGg.',
      '.gGg..gGg...gGgg..',
      '..r....r.....r....',
      '..r...r.......r...',
      '...r..r......r....',
    ],
  },
  driftwood: {
    palette: { W: '#6a4a2a', w: '#8a6a44' },
    rows: [
      '...............w..',
      '..w...........ww..',
      '..ww.........ww...',
      '...ww.......ww....',
      '....ww.....wW.....',
      '.....wW...wW......',
      '......wWwwW.......',
      '.......wWWw.......',
      '......wWWWWw......',
      '.....wWWwWWWw.....',
      '...wwWWw..wWWww...',
      '..wWWww....wwWWw..',
    ],
  },
  leaves: {
    palette: { b: '#8a5a2a', B: '#b07a3a', o: '#c0702a', O: '#e09a4a' },
    rows: [
      '...bb.....oo....',
      '.bbBBb.ooOOo.bb.',
      'bBBBbboOOOoobBBb',
      '.bbbb..oooo.bbb.',
    ],
  },
  slate_cave: {
    palette: { s: '#4a5260', S: '#6a7486', k: '#1a1c24' },
    rows: [
      '...ssssssssss...',
      '..sSSSSSSSSSSs..',
      '.sSSSSSSSSSSSSs.',
      'ssssssssssssssss',
      '.sSkkkkkkkkkkSs.',
      '.sSkkkkkkkkkkSs.',
      '.sSkkkkkkkkkkSs.',
      '.sSkkkkkkkkkkSs.',
      'ssSSkkkkkkkkSSss',
      'ssssssssssssssss',
    ],
  },

  // ---------------------------------------------------------- Bassin koï
  mud: {
    palette: { M: '#6a5a40', m: '#54462f' },
    rows: [
      '.....mmmmmm.......',
      '..mmmMMMMMMmmm....',
      '.mMMMMmMMMMMMMmmm.',
      'mMMMMMMMMMMmMMMMMm',
    ],
  },
  river_pebbles: {
    palette: { W: '#d8d4cc', w: '#a8a49c', G: '#9aa0a8', g: '#707680' },
    rows: [
      '..ww.....gg.....',
      '.wWWw.gg.gGGg.w.',
      'wWWWWgGGgGGGGwWw',
      'wWWWWgGGGgGGGwWw',
      '.wwwwwgggggggww.',
    ],
  },
  mussel: {
    palette: { k: '#1e2230', B: '#3a4260', b: '#6a78a0' },
    rows: [
      '...kkkk...',
      '.kkBBBBkk.',
      'kBBbBBbBBk',
      'kBBBBBBBBk',
      '.kkkkkkkk.',
    ],
  },
  lily: {
    palette: { p: '#ffb0d0', P: '#ff7aa8', g: '#3f8f4a', G: '#5faf5a', s: '#4a7a3a' },
    rows: [
      '......p.p.........',
      '.....pPpPp........',
      '..gggGpppPgggg....',
      '.gGGGGGGGGGGGGGgg.',
      'gGGGGGGGGGGGGGGGGg',
      '.ggggg..gggggggg..',
      '........s.........',
      '........s.........',
      '.........s........',
    ],
  },
  iris: {
    palette: { v: '#b07ae8', V: '#7a4ad8', y: '#ffd84a', g: '#6fbf5a', G: '#3f8f3a', s: '#8f8778' },
    rows: [
      '....vv....',
      '...vVVv...',
      '..vVyVVv..',
      '...vVVv...',
      '....gg....',
      '.g..gg..g.',
      '.gg.gg.gg.',
      '..g.gg.g..',
      '..gggggg..',
      '...gggg...',
      '...gGGg...',
      '...gGGg...',
      '....GG....',
      '....GG....',
      '...ssss...',
      '..ssssss..',
    ],
  },
  lantern: {
    palette: { s: '#8a8478', S: '#b0aa9c', y: '#ffd86a', Y: '#fff3b0' },
    rows: [
      '....ss....',
      '...sSSs...',
      '.ssSSSSss.',
      'ssssssssss',
      '.sS.yy.Ss.',
      '.sS.yY.Ss.',
      '.sS.yy.Ss.',
      'ssssssssss',
      '..sSSSSs..',
      '...sSSs...',
      '...sSSs...',
      '...sSSs...',
      '..sSSSSs..',
      '.ssSSSSss.',
      'ssssssssss',
      'ssssssssss',
    ],
  },
  shishi: {
    palette: { g: '#b8d86a', G: '#8aac3a', w: '#bfefff', r: '#8a8478', R: '#a8a294' },
    rows: [
      '..........gG',
      '........gGg.',
      '......gGg...',
      '....gGgG....',
      '...gGg.G....',
      '..wg...G....',
      '..w....G....',
      '..w....G....',
      '.www...G....',
      '..w...GG....',
      '......GG....',
      '......GG....',
      '......GG....',
      '.....rrrr...',
      '....rrRRrr..',
      '...rrRRRRrr.',
    ],
  },
  bridge: {
    palette: { r: '#e0402a', R: '#c0302a', w: '#b03a2a', W: '#d04a30', s: '#8a8478' },
    rows: [
      '.r..................r.',
      '.rrrrrrrrrrrrrrrrrrrr.',
      '.r....r....r....r...r.',
      '..wwwwwwwwwwwwwwwwww..',
      '.wWWWWWWWWWWWWWWWWWWw.',
      'wW..................Ww',
      'wW..................Ww',
      'RR..................RR',
      'RR..................RR',
      'ss..................ss',
    ],
  },
  // ------------------------------------------------------------ Mangrove
  mangrove_roots: {
    palette: { W: '#6a4a2a', w: '#8a6a44' },
    rows: [
      '........WW........',
      '........Ww........',
      '.......wWWw.......',
      '......wW..Ww......',
      '.....wW....Ww.....',
      '....wW..ww..Ww....',
      '...wW..wWWw..Ww...',
      '..wW..wW..Ww..Ww..',
      '.wW..wW....Ww..Ww.',
      'wW..wW......Ww..Ww',
      'W..wW........Ww..W',
      '..wW..........Ww..',
      '.wW............Ww.',
      'wW..............Ww',
    ],
  },
  mudflat: {
    palette: { m: '#6a5a48', M: '#8a7a60', o: '#2b2238' },
    rows: ['.....mmmmmm.......', '..mmmMMoMMMmmm....', '.mMMoMmMMMMoMMmmm.', 'mMMMMMMMMMMmMMMMMm'],
  },
  oyster_bed: {
    palette: { o: '#4a4a52', G: '#8a8a90', g: '#a8a8b0', w: '#f0ece8' },
    rows: ['...oo....oo...', '.ooGGoo.oGGoo.', 'oGGgGGGoGGgGGo', 'oGGGGGGGGGGGGo', '.oGGwGGGGGwGo.', '..oooooooooo..'],
  },
  overhang: {
    palette: { b: '#6a4a2a', g: '#5faf4a', G: '#3f8f3a', i: '#2b2238' },
    rows: [
      'bbbbbbbbbbbbbbbb....',
      '..gg..gg.bbbbb.gg...',
      '.gGgg.gGg...bbbGg...',
      '..gg...g......bbi...',
      '...............b....',
    ],
  },
  propagules: {
    palette: { b: '#6a8a3a', g: '#6fcf5a', G: '#3f9f3a', m: '#6a5a48' },
    rows: [
      '..g.....g...', '.gGg...gGg..', '..g.....g.g.', '..b.....bgGg', '..b.....b.g.', '..b.....b.b.', '..b..g..b.b.',
      '..b.gGg.b.b.', '..b..g..b.b.', '..b..b..b.b.', '..b..b..b.b.', '..b..b..b.b.', '.mmmmmmmmmmm', 'mmmmmmmmmmmm',
    ],
  },
  brackish_stones: {
    palette: { G: '#8a9a80', g: '#5a6a50', w: '#8fcf6a' },
    rows: ['...gg.........', '..gwGg...gg...', '.gGGGGg.gwGg..', 'gGGGGGGgGGGGg.', 'gGGGGGGgGGGGGg', '.ggggggggggggg'],
  },
  fiddler_crab: {
    palette: { R: '#e8603a', C: '#5a7ab0', o: '#2b2238' },
    rows: ['..o...o..', 'RR.ooooo.', 'RRooCCCoo', '..oCCCCCo', '..o.o.o.o'],
  },
  old_pirogue: {
    palette: { W: '#9a6a3a', w: '#7a4a2a', o: '#2b2238', m: '#6a5a48' },
    rows: [
      'o..................o',
      'oo................oo',
      '.oWWWWWWWWWWWWWWWWo.',
      '.owwwwwwwwwwwwwwwwo.',
      '..oWWWWWWWWWWWWWWo..',
      '...oooooooooooooo...',
      '....mmm......mmm....',
    ],
  },

  // ------------------------------------------------------------ Banquise
  ice_block: {
    palette: { W: '#eaf6fc', w: '#ffffff', B: '#bfe0f0', o: '#5a8ab0' },
    rows: [
      '..oooooooo....',
      '.oWWWWWWWWo...',
      'oWwWWWWWWWWo..',
      'oWwBBWWWWWWBo.',
      'oWBBBWWWWWBBBo',
      'oWWBWWWWWWBBBo',
      'oWWWWWWWBBBBWo',
      'oBWWWWWWWBBWWo',
      'oBBWWWWWWWWWWo',
      'oBBBWWWWWWWBBo',
      '.oBBBBBBBBBBo.',
      '..oooooooooo..',
    ],
  },
  ice_floe: {
    palette: { W: '#eaf6fc', w: '#ffffff', B: '#bfe0f0', o: '#5a8ab0' },
    rows: [
      'oooooooooooooooooooo',
      'oWWWWwWWWWWWWWwWWWWo',
      'oBBWWWWWWWWBBWWWWBBo',
      '.oBBBBBBBBBBBBBBBBo.',
      '..oooooooooooooooo..',
    ],
  },
  kelp: {
    palette: { k: '#b8a040', K: '#7a6a2a', s: '#8a8478' },
    rows: [
      '...k......', '..kK...k..', '..kK..kK..', '...K..kK..', '..kK...K..', '..kK..kK..', '...K..kK.k',
      '..kK...KkK', '..kK..kK.K', '...K..kK.K', '..kK...K.K', '..kK..kK.K', '...K..kKkK', '..kK...K.K',
      '...K..kK.K', '...K...K.K', '...K..KK.K', '...KK.K.KK', '....KKK.K.', '.....KKK..', '...ssssss.', '..ssssssss',
    ],
  },
  cold_stones: {
    palette: { G: '#9aa8b8', g: '#6a7888', w: '#ffffff' },
    rows: ['...gg.........', '..gwGg...gg...', '.gGGGGg.gwGg..', 'gGGGGGGgGGGGg.', 'gGGGGGGgGGGGGg', '.ggggggggggggg'],
  },
  ice_cave: {
    palette: { s: '#6a8ab0', S: '#bfe0f0', k: '#1a2a40' },
    rows: [
      '...ssssssssss...',
      '..sSSSSSSSSSSs..',
      '.sSSSSSSSSSSSSs.',
      'ssssssssssssssss',
      '.sSkkkkkkkkkkSs.',
      '.sSkkkkkkkkkkSs.',
      '.sSkkkkkkkkkkSs.',
      '.sSkkkkkkkkkkSs.',
      'ssSSkkkkkkkkSSss',
      'ssssssssssssssss',
    ],
  },
  urchins: {
    palette: { k: '#3a2a4a', p: '#8a4a9a' },
    rows: ['..k.k..k.k..', '.kkpkk.kkpkk', 'kkpppkkkpppk', '.kpppk.kpppk', '..kkk...kkk.'],
  },
  old_anchor: {
    palette: { A: '#6a6a7a', o: '#4a4a5a', r: '#a8583a' },
    rows: [
      '....ooo.....', '....oAo.....', '....ooo.....', '..AAAAAAA...', '.....A......', '.....A......', '.....A......',
      '.....A......', '.....A......', 'A....A....A.', 'AA...A...AA.', '.AA..A..AA..', '..AAAAAAA...', '...rrrrr....',
    ],
  },

  // ------------------------------------------------------------- Abysses
  vent: {
    palette: { g: '#5a5a6a', G: '#8a8a9a', o: '#1a1a22', y: '#ffd86a', R: '#c8502a', K: '#3a3440' },
    rows: [
      '....gggg....', '...gGGGGg...', '....gGGg....', '....oyyo....', '...oRyyRo...', '...oRRRRo...', '..oRKRRKRo..',
      '..oKKRKKKo..', '..oKKKKRKo..', '.oKKRKKKKKo.', '.oKKKKKRKKo.', '.oKRKKKKKKo.', 'oKKKKKRKKKKo', 'oKKRKKKKKRKo',
      'oKKKKKKKKKKo', 'oooooooooooo',
    ],
  },
  glow_coral: {
    palette: { c: '#7af0ff', p: '#ff7ae0', b: '#3a6a8a', r: '#2a2a3a' },
    rows: [
      '..c....p....', '..b..c.b..p.', '.bb..b.bb.b.', '..b..bb.b.bb', '..bb.b..bbb.', '...b.b..b...',
      '...bbb.bb...', '....bb.b....', '....bbbb....', '.....bb.....', '....rrrr....', '...rrrrrr...',
    ],
  },
  abyss_rocks: {
    palette: { G: '#3a3a4a', g: '#2a2a36', w: '#5a5a6a' },
    rows: ['...gg.........', '..gwGg...gg...', '.gGGGGg.gwGg..', 'gGGGGGGgGGGGg.', 'gGGGGGGgGGGGGg', '.ggggggggggggg'],
  },
  wreck: {
    palette: { W: '#5a4a3a', w: '#7a6a4a', k: '#1a1a22', o: '#2a2226', r: '#3a3a4a' },
    rows: [
      '.......o............',
      '.......o............',
      '.......o......o.....',
      '.....ooooo...ooo....',
      '....oWWWWWoooWWWo...',
      '...oWwWWwWWWWWwWWo..',
      '..oWWWWWWWoWWWWWWWo.',
      '.oWWkkWWWWWWWkkWWWWo',
      'oWWWkkWWWWWWWkkWWWWo',
      'oWWWWWWWWWWWWWWWWWo.',
      '.oooooooooooooooooo.',
      'rrrrrrrrrrrrrrrrrrrr',
    ],
  },
  whale_fall: {
    palette: { b: '#e8e0c8', B: '#c8bca0', r: '#e8453c' },
    rows: [
      '...b..b..b..b..b....',
      '..b..b..b..b..b..b..',
      '..b..b..b..b..b..b..',
      'bbbbbbbbbbbbbbbbbbbb',
      'BbBbBbBbBbBbBbBbBbBb',
      '..r....r.....r......',
    ],
  },
  sea_pen: {
    palette: { p: '#ff8ad0', s: '#8a5a8a', r: '#2a2a3a' },
    rows: [
      '...p....', '..ppp...', '.p.p.p..', '..ppp...', '.p.p.p..', '..ppp...', '.p.p.p..', '..ppp...',
      '.p.p.p..', '..ppp...', '...s....', '...s....', '...s....', '...s....', '..sss...', '.rrrrr..',
    ],
  },
  glass_sponge: {
    palette: { w: '#e8f4f8', r: '#2a2a3a' },
    rows: [
      '..wwwwww..', '.w.w..w.w.', '.wwwwwwww.', '.w.w..w.w.', '.wwwwwwww.', '.w.w..w.w.', '.wwwwwwww.',
      '.w.w..w.w.', '.wwwwwwww.', '..w.w.w...', '..wwwwww..', '...w..w...', '...wwww...', '..rrrrrr..',
    ],
  },
};
