// Sprites des objets de décor (ancrés en bas, sauf « surface »).
import type { DecorId } from '../../data/decor';
import type { SpriteDef } from '../SpriteFactory';

export const DECOR_SPRITES: Record<DecorId, SpriteDef> = {
  // ------------------------------------------------------------- Récif
  live_rock: {
    palette: { R: '#8e8497', r: '#6c6378', p: '#ff8fb0', P: '#e0608a' },
    rows: [
      '......rrrr......',
      '....rrRRRrrp....',
      '..prrRRRRRRrr...',
      '.rRRRRpPRRRRRr..',
      'rRRRRRRRRRRpRRr.',
      'rRRpRRRRRRRRRRRr',
      'rRRRRRRRRpPRRRRr',
      'rrRRRRRRRRRRRRrr',
      '.rrrrrrrrrrrrrr.',
    ],
  },
  anemone: {
    palette: { t: '#c84fd0', p: '#ff9ec8', P: '#e0709e', b: '#8e6a5a' },
    rows: [
      '..t..t.t..t...',
      '.tpt.tpt.tpt..',
      '.pp.tpptpp.pt.',
      'tpp.pppppp.ppt',
      '.pppppppppppp.',
      '..pppppppppp..',
      '...PPPPPPPP...',
      '...PPPPPPPP...',
      '....PPPPPP....',
      '....bbbbbb....',
      '...bbbbbbbb...',
    ],
  },
  branch_coral: {
    palette: { y: '#ffb88a', o: '#ff7a4a', O: '#9a8a80' },
    rows: [
      '..y.....y....',
      '..o..y..o..y.',
      '.oo..o.oo..o.',
      '..o..oo.o.oo.',
      '..oo.o..ooo..',
      '...o.o..o....',
      '...ooo.oo..o.',
      '....oo.o..oo.',
      '....oooo.oo..',
      '.....ooooo...',
      '......ooo....',
      '......oOo....',
      '.....OOOOO...',
      '....OOOOOOO..',
    ],
  },
  brain_coral: {
    palette: { g: '#9fbf4a', G: '#d8e87a', r: '#8e8497' },
    rows: [
      '....gggggg....',
      '..gGgGGgGgGg..',
      '.gGGgGgGGgGGg.',
      'gGgGGgGGgGgGGg',
      'gGGgGGgGgGGgGg',
      'gGgGGgGgGGgGGg',
      '.rrrrrrrrrrrr.',
      'rrrrrrrrrrrrrr',
    ],
  },
  seagrass: {
    palette: { g: '#6fcf6a', G: '#3f9f4a', s: '#d8bf85' },
    rows: [
      '..g.....g...',
      '..g..g..g...',
      '.gG..g..Gg..',
      '.gG..gG.Gg.g',
      '..G.gG..G..g',
      '..Gg.G.gG.gG',
      '..G..G.g..G.',
      '.gG..Gg..gG.',
      '.g.G.G...G..',
      '...G.G.g.G..',
      '...GgG.gGG..',
      '....GG..G...',
      '....GGgGG...',
      '....sGGGs...',
      '...ssssssss.',
    ],
  },
  gorgonian: {
    palette: { p: '#c77ae0', P: '#8a3fb0', r: '#8e8497' },
    rows: [
      '...p.p..p.p...',
      '..pPpPppPpPp..',
      '.pPpPpPPpPpPp.',
      'pPpPpPpPPpPpPp',
      '.pPpPpPpPpPpP.',
      'pPpPpPPpPPpPpp',
      '.pPpPpPpPpPpP.',
      '..pPpPpPpPpP..',
      '...pPpPPpPp...',
      '....pPpPpP....',
      '.....pPPp.....',
      '......PP......',
      '......PP......',
      '......PP......',
      '.....rrrr.....',
      '....rrrrrr....',
    ],
  },
  giant_clam: {
    palette: { b: '#2a6fd8', B: '#4fc3f7', c: '#9ff0ff', S: '#e8dcc8', s: '#c8b8a0', k: '#8a7a68' },
    rows: [
      '..kkkkkkkkkk..',
      '.kbBbBbBbBbBk.',
      'kbBcBcBcBcBcBk',
      'kSSSSSSSSSSSSk',
      '.kSsSsSsSsSsk.',
      '..kSSSSSSSSk..',
      '...kkkkkkkk...',
    ],
  },
  treasure: {
    palette: { b: '#6a3f1f', B: '#9a5a2a', y: '#f0c040', Y: '#fff080', k: '#3a2010' },
    rows: [
      '..bbbbbbbbb..',
      '.bBBBBBBBBBb.',
      'bBByBBBBByBBb',
      'bbbbbbbbbbbbb',
      'yyyyyyYyyyyyy',
      'bBBBBByBBBBBb',
      'bBBBBBkBBBBBb',
      'bBByBBBBByBBb',
      'bBBBBBBBBBBBb',
      'bbbbbbbbbbbbb',
    ],
  },

  // ---------------------------------------------------------- Amazonie
  stones: {
    palette: { G: '#b0a898', g: '#847c6e', w: '#d6d0c4' },
    rows: [
      '...gg.........',
      '..gwGg...gg...',
      '.gGGGGg.gwGg..',
      'gGGGGGGgGGGGg.',
      'gGGGGGGgGGGGGg',
      '.ggggggggggggg',
    ],
  },
  sand_bank: {
    palette: { S: '#f0e2c0', s: '#d8c49a' },
    rows: [
      '......ssssss......',
      '...ssSSSSSSSSss...',
      '.ssSSSSsSSSSSSSss.',
      'sSSSSSSSSSSsSSSSSs',
    ],
  },
  sword_plant: {
    palette: { g: '#5fbf4a', G: '#2f8f3a', s: '#9f7f55', S: '#c9a878' },
    rows: [
      '......g.......',
      '..g...gG...g..',
      '..gG..gG..Gg..',
      '...gG.gG.Gg...',
      '.g..gGgGGg..g.',
      '.gG..gGGg..Gg.',
      '..gG.gGGg.Gg..',
      '...gGgGGgGg...',
      '....gGGGGg....',
      '.....gGGg.....',
      '......GG......',
      '......GG......',
      '.....sssS.....',
      '....ssssss....',
    ],
  },
  vallisneria: {
    palette: { g: '#6fcf5a', G: '#3f9f3a', s: '#9f7f55' },
    rows: [
      '..g.......',
      '..g....g..',
      '..g...g...',
      '.g..g.g...',
      '.g..g..g..',
      '.g..g..g.g',
      '..g.g..g.g',
      '..g..g.g.g',
      '..g..g.gg.',
      '..gg.g..g.',
      '...g.g..g.',
      '...g..g.g.',
      '...g..g.g.',
      '...gg.g.g.',
      '....g.gg..',
      '....g.g...',
      '....gGg...',
      '....gGg...',
      '....GgG...',
      '....GGG...',
      '...ssss...',
      '..ssssss..',
    ],
  },
  floating: {
    palette: { G: '#8fdf6a', g: '#5faf4a', r: '#c8b89a' },
    rows: [
      '.GGg..gGG...gGGg..',
      'gGGGgGGGGggGGGGGg.',
      '.gGg..gGg...gGgg..',
      '..r....r.....r....',
      '..r...r.......r...',
      '...r..r......r....',
    ],
  },
  driftwood: {
    palette: { W: '#6a4a2a', w: '#8a6a44' },
    rows: [
      '...............w..',
      '..w...........ww..',
      '..ww.........ww...',
      '...ww.......ww....',
      '....ww.....wW.....',
      '.....wW...wW......',
      '......wWwwW.......',
      '.......wWWw.......',
      '......wWWWWw......',
      '.....wWWwWWWw.....',
      '...wwWWw..wWWww...',
      '..wWWww....wwWWw..',
    ],
  },
  leaves: {
    palette: { b: '#8a5a2a', B: '#b07a3a', o: '#c0702a', O: '#e09a4a' },
    rows: [
      '...bb.....oo....',
      '.bbBBb.ooOOo.bb.',
      'bBBBbboOOOoobBBb',
      '.bbbb..oooo.bbb.',
    ],
  },
  slate_cave: {
    palette: { s: '#4a5260', S: '#6a7486', k: '#1a1c24' },
    rows: [
      '...ssssssssss...',
      '..sSSSSSSSSSSs..',
      '.sSSSSSSSSSSSSs.',
      'ssssssssssssssss',
      '.sSkkkkkkkkkkSs.',
      '.sSkkkkkkkkkkSs.',
      '.sSkkkkkkkkkkSs.',
      '.sSkkkkkkkkkkSs.',
      'ssSSkkkkkkkkSSss',
      'ssssssssssssssss',
    ],
  },

  // ---------------------------------------------------------- Bassin koï
  mud: {
    palette: { M: '#6a5a40', m: '#54462f' },
    rows: [
      '.....mmmmmm.......',
      '..mmmMMMMMMmmm....',
      '.mMMMMmMMMMMMMmmm.',
      'mMMMMMMMMMMmMMMMMm',
    ],
  },
  river_pebbles: {
    palette: { W: '#d8d4cc', w: '#a8a49c', G: '#9aa0a8', g: '#707680' },
    rows: [
      '..ww.....gg.....',
      '.wWWw.gg.gGGg.w.',
      'wWWWWgGGgGGGGwWw',
      'wWWWWgGGGgGGGwWw',
      '.wwwwwgggggggww.',
    ],
  },
  mussel: {
    palette: { k: '#1e2230', B: '#3a4260', b: '#6a78a0' },
    rows: [
      '...kkkk...',
      '.kkBBBBkk.',
      'kBBbBBbBBk',
      'kBBBBBBBBk',
      '.kkkkkkkk.',
    ],
  },
  lily: {
    palette: { p: '#ffb0d0', P: '#ff7aa8', g: '#3f8f4a', G: '#5faf5a', s: '#4a7a3a' },
    rows: [
      '......p.p.........',
      '.....pPpPp........',
      '..gggGpppPgggg....',
      '.gGGGGGGGGGGGGGgg.',
      'gGGGGGGGGGGGGGGGGg',
      '.ggggg..gggggggg..',
      '........s.........',
      '........s.........',
      '.........s........',
    ],
  },
  iris: {
    palette: { v: '#b07ae8', V: '#7a4ad8', y: '#ffd84a', g: '#6fbf5a', G: '#3f8f3a', s: '#8f8778' },
    rows: [
      '....vv....',
      '...vVVv...',
      '..vVyVVv..',
      '...vVVv...',
      '....gg....',
      '.g..gg..g.',
      '.gg.gg.gg.',
      '..g.gg.g..',
      '..gggggg..',
      '...gggg...',
      '...gGGg...',
      '...gGGg...',
      '....GG....',
      '....GG....',
      '...ssss...',
      '..ssssss..',
    ],
  },
  lantern: {
    palette: { s: '#8a8478', S: '#b0aa9c', y: '#ffd86a', Y: '#fff3b0' },
    rows: [
      '....ss....',
      '...sSSs...',
      '.ssSSSSss.',
      'ssssssssss',
      '.sS.yy.Ss.',
      '.sS.yY.Ss.',
      '.sS.yy.Ss.',
      'ssssssssss',
      '..sSSSSs..',
      '...sSSs...',
      '...sSSs...',
      '...sSSs...',
      '..sSSSSs..',
      '.ssSSSSss.',
      'ssssssssss',
      'ssssssssss',
    ],
  },
  shishi: {
    palette: { g: '#b8d86a', G: '#8aac3a', w: '#bfefff', r: '#8a8478', R: '#a8a294' },
    rows: [
      '..........gG',
      '........gGg.',
      '......gGg...',
      '....gGgG....',
      '...gGg.G....',
      '..wg...G....',
      '..w....G....',
      '..w....G....',
      '.www...G....',
      '..w...GG....',
      '......GG....',
      '......GG....',
      '......GG....',
      '.....rrrr...',
      '....rrRRrr..',
      '...rrRRRRrr.',
    ],
  },
  bridge: {
    palette: { r: '#e0402a', R: '#c0302a', w: '#b03a2a', W: '#d04a30', s: '#8a8478' },
    rows: [
      '.r..................r.',
      '.rrrrrrrrrrrrrrrrrrrr.',
      '.r....r....r....r...r.',
      '..wwwwwwwwwwwwwwwwww..',
      '.wWWWWWWWWWWWWWWWWWWw.',
      'wW..................Ww',
      'wW..................Ww',
      'RR..................RR',
      'RR..................RR',
      'ss..................ss',
    ],
  },
};
